<?php
$clearance = is_array($clearance ?? null) ? $clearance : [];
$items     = is_array($items ?? null) ? $items : [];
$employee  = is_array($employee ?? null) ? $employee : [];
$name      = trim(($employee['first_name'] ?? '') . ' ' . ($employee['middle_name'] ?? '') . ' ' . ($employee['last_name'] ?? ''));
$today     = date('F j, Y');
?>
<div class="print-page">
    <div class="page-header">
        <p class="agency">Republic of the Philippines</p>
        <h1>Clearance Form</h1>
        <h2>Barangay Human Resources Information System</h2>
    </div>

    <div style="border:1px solid #999; padding:10px; margin-bottom:16px;">
        <div class="two-col">
            <div class="field-pair">
                <span class="field-label">Employee Name</span>
                <span class="field-value"><?= e(strtoupper($name)) ?></span>
            </div>
            <div class="field-pair">
                <span class="field-label">Employee Code</span>
                <span class="field-value"><?= e((string)($employee['employee_code']??'-')) ?></span>
            </div>
            <div class="field-pair">
                <span class="field-label">Clearance Type</span>
                <span class="field-value"><?= e((string)($clearance['clearance_type']??'-')) ?></span>
            </div>
            <div class="field-pair">
                <span class="field-label">Effective Date</span>
                <span class="field-value"><?= e((string)($clearance['effective_date']??'-')) ?></span>
            </div>
            <div class="field-pair">
                <span class="field-label">Purpose</span>
                <span class="field-value"><?= e((string)($clearance['purpose']??'-')) ?></span>
            </div>
            <div class="field-pair">
                <span class="field-label">Status</span>
                <span class="field-value"><?= e((string)($clearance['status']??'-')) ?></span>
            </div>
        </div>
    </div>

    <h3>Sign-Off Items</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Office / Department</th>
                <th>Responsible Person</th>
                <th>Status</th>
                <th>Date Cleared</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($items === []): ?>
                <tr><td colspan="6" style="text-align:center;color:#777;padding:12px;">No clearance items found.</td></tr>
            <?php else: ?>
                <?php foreach ($items as $i => $item): ?>
                    <tr>
                        <td><?= e((string)($i + 1)) ?></td>
                        <td><?= e((string)($item['office_name']??'-')) ?></td>
                        <td><?= e((string)($item['responsible_person']??'-')) ?></td>
                        <td><?= e((string)($item['status']??'-')) ?></td>
                        <td><?= e((string)($item['cleared_at']??'-')) ?></td>
                        <td><?= e((string)($item['remarks']??'')) ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="signature-block" style="margin-top:32px;">
        <div class="signature-line">
            <br><br>
            <strong><?= e(strtoupper($name)) ?></strong><br>
            <span class="label">Employee Signature / Date</span>
        </div>
        <div class="signature-line">
            <br><br>
            <strong>______________________________</strong><br>
            <span class="label">HR Officer</span>
        </div>
        <div class="signature-line">
            <br><br>
            <strong>______________________________</strong><br>
            <span class="label">Approving Authority</span>
        </div>
    </div>

    <p style="margin-top:20px; font-size:9pt; color:#777; text-align:center; border-top:1px solid #ccc; padding-top:8px;">
        This clearance form is generated by the Barangay HRIS. &bull; Printed: <?= e($today) ?>
    </p>
</div>
