<?php
$employee = is_array($employee ?? null) ? $employee : [];
$records  = is_array($records ?? null) ? $records : [];
$name     = trim(($employee['first_name'] ?? '') . ' ' . ($employee['middle_name'] ?? '') . ' ' . ($employee['last_name'] ?? ''));
$today    = date('F j, Y');
?>
<div class="print-page">
    <div class="page-header">
        <p class="agency">Republic of the Philippines</p>
        <h1>Service Record</h1>
        <h2>Barangay Human Resources Information System</h2>
        <p class="agency">Generated: <?= e($today) ?></p>
    </div>

    <div class="two-col" style="margin-bottom:16px; border:1px solid #999; padding:10px;">
        <div>
            <span class="field-label">Name</span>
            <span class="field-value"><?= e(strtoupper($name)) ?></span>
        </div>
        <div>
            <span class="field-label">Employee Code</span>
            <span class="field-value"><?= e((string)($employee['employee_code']??'-')) ?></span>
        </div>
        <div>
            <span class="field-label">Department</span>
            <span class="field-value"><?= e((string)($employee['department_name']??'-')) ?></span>
        </div>
        <div>
            <span class="field-label">Designation</span>
            <span class="field-value"><?= e((string)($employee['designation_name']??'-')) ?></span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Position Title</th>
                <th>Status</th>
                <th>Office / Unit</th>
                <th>SG / Step</th>
                <th>Monthly Salary</th>
                <th>Date From</th>
                <th>Date To</th>
                <th>Sep. Type</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($records === []): ?>
                <tr><td colspan="8" style="text-align:center; color:#777; padding:16px;">No service records found.</td></tr>
            <?php else: ?>
                <?php foreach ($records as $rec): ?>
                    <tr>
                        <td><?= e((string)($rec['position_title']??'-')) ?><?= (int)($rec['is_current']??0)===1 ? ' <strong>(Current)</strong>' : '' ?></td>
                        <td><?= e((string)($rec['appointment_status']??'-')) ?></td>
                        <td><?= e((string)($rec['office_unit']??'-')) ?><?= $rec['division']??'' ? '<br><small>'.e((string)$rec['division']).'</small>' : '' ?></td>
                        <td><?= e((string)($rec['salary_grade']??'-')) ?><?= $rec['salary_step']??'' ? '/'.e((string)$rec['salary_step']) : '' ?></td>
                        <td><?= $rec['monthly_salary']??'' ? '₱'.number_format((float)$rec['monthly_salary'],2) : '-' ?></td>
                        <td><?= e((string)($rec['date_from']??'-')) ?></td>
                        <td><?= e((string)($rec['date_to']??'Present')) ?></td>
                        <td><?= e((string)($rec['separation_type']??'-')) ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="signature-block" style="margin-top:32px;">
        <div class="signature-line">
            <br><br>
            <strong><?= e(strtoupper($name)) ?></strong><br>
            <span class="label">Employee Signature</span>
        </div>
        <div class="signature-line">
            <br><br>
            <strong>______________________________</strong><br>
            <span class="label">HR Officer / Authorized Signatory</span>
        </div>
    </div>

    <p style="margin-top:24px; font-size:9pt; color:#777; text-align:center; border-top:1px solid #ccc; padding-top:8px;">
        This document is an official record generated by the Barangay HRIS. &bull; Printed: <?= e($today) ?>
    </p>
</div>
